default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues: "*"
      threads: 3
      processes: <%= ENV.fetch("JOB_CONCURRENCY", 1) %>
      polling_interval: 0.1

development:
  <<: *default
  # Em development, usar apenas 1 processo e 1 thread para simplificar
  workers:
    - queues: "*"
      threads: 1
      processes: 1
      polling_interval: 1

test:
  <<: *default

production:
  <<: *default
